name: Total Open Station

# Setup
title: Total Open Station
description: 'Total Open Station downloads data from total stations.'
url: http://tops.iosa.it/


author:
  name: 'Stefano Costa'
  url: http://steko.iosa.it/

gems:
  - jekyll-feed
  - jekyll-mentions
  - jekyll-seo-tag
